name: Package to ghcr.io
on:
  push:
    branches:
      - main
jobs:
    komm-docker-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write  
        steps:
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.TOKEN }}
        - name: Set variable as output
          id: vars
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        - name: Build Kafka-Producer image
          run: |
                 docker build ./producer/ --tag ghcr.io/florina-alfred/komm-pro:latest
                 docker push ghcr.io/florina-alfred/komm-pro:latest
                 docker tag ghcr.io/florina-alfred/komm-pro:latest  ghcr.io/florina-alfred/komm-pro:${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/komm-pro:${{ steps.vars.outputs.sha_short }}
        - name: Build Kafka-Consumer image
          run: |
                 docker build ./consumer/ --tag ghcr.io/florina-alfred/komm-con:latest
                 docker push ghcr.io/florina-alfred/komm-con:latest
                 docker tag ghcr.io/florina-alfred/komm-con:latest  ghcr.io/florina-alfred/komm-con:${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/komm-con:${{ steps.vars.outputs.sha_short }}
